### ISSUE TITLE
GDPR compatibility 

### ISSUE THREAD

**Issue by ibes** [rinvex/laravel-statistics#12]
Hi there,

I would like to have some lightweight statistics in my Laravel project and this package looks perfect. 

Besides: I guess it tracks more information than I would want to have. Especially the IP address should likely be anonymized to be more compliant to the GDPR. Do you have checked in with the requirements?
Is there a way to avoid tracking certain data or anonymize them?
As far as I know for Google Analytics it is required to drop the last digits of the IP address. I imagine that should still be fine enough to pull the geo-coordinates out of it. 

I am mostly interested in:
- what pages are popular
- where do my users come from
- what are they doing on my site

**Comment by Omranic** [comment]
@ibes thank you for your feedback, I'd love to see some PRs for GDPR compatibility :)
