### ISSUE TITLE
Package doesnt install on Laravel 7.14.1

### ISSUE THREAD

**Issue by mrmmg** [rinvex/laravel-statistics#20]
Hi
I want to install package on laravel 7 but I got errors. it seems the package cannot install on Laravel 7.14.1 and later...
![Annotation 2020-06-03 234611](https://user-images.githubusercontent.com/30490118/83679539-ce4d5800-a5f4-11ea-8c2a-681bfb947db6.png)

**Comment by Omranic** [comment]
Probably it's because of your PHP version, not Laravel version. This package requires PHP v7.4 as minimum requirement, which version do you currently have?

**Comment by Omranic** [comment]
BTW you can use v3.x releases for lower requirement, which requires PHP v7.2 .. feel free to reopen this issue..
