### ISSUE TITLE
Stats for API

### ISSUE THREAD

**Issue by FarhanShares** [rinvex/laravel-statistics#31]
By default it's not logging the API routes so I just added the middleware that was used in the web middleware group in api middleware group as well; with no luck. I'm willing to provide more info. 

Does the package really has support for logging API requests as well?

**Comment by Omranic** [comment]
Rinvex Statistics has a `\Rinvex\Statistics\Http\Middleware\TrackStatistics` middleware that attach itself automatically to the `web` middleware group, that's how it works out-of-the-box with zero configuration.

So by default it doesn't run on API requests, but if you attached it manually to the API middleware group or on your API routes, it should work. If you believe it doesn't please provide more info to troubleshoot the use case. One suggestion to do before that, is to `dd` inside the middleware itself to make sure it's running, and to check what's going on..

Please note how it works, it stores request data on each hit, but it doesn't crunch it everytime, that happens randomly for performance reasons. Refer to https://github.com/rinvex/laravel-statistics/blob/df91a73b89304808f0841bf496673ef9eee26dc7/src/Http/Middleware/TrackStatistics.php#L38-L63
