### ISSUE TITLE
torann/geoip function geoip causing job to fail

### ISSUE THREAD

**Issue by nagi1** [rinvex/laravel-statistics#32]
Hey, thanks for such wonderful tool I really enjoyed using it.

After intense debuging session I found that the `geoip()` function was throwing exception "Current cache driver does not support tagging", which was caught by try catch block causing the job to fail silently without even log the exception.

I solved this tempraly by creating geoip.php in config file and override config key `  'cache_tags'`

`return [
    'cache_tags' => []
];`

Laravel version: 7
Package version: 4.1.0

I'm wondering if we can first fix the try catch block, and what do you suggest to solve this?

**Comment by Omranic** [comment]
Thank you @nagi1 for reporting this, I would be happy to consider a PR :)
