### ISSUE TITLE
Error if user agent empty 500 error

### ISSUE THREAD

**Issue by CrazyBoy49z** [rinvex/laravel-statistics#39]
UAParser\Parser::parse(): Argument #1 ($userAgent) must be of type string, null given, called in .../vendor/rinvex/laravel-statistics/src/Jobs/CrunchStatistics.php on line 46 {"exception":"[object] (TypeError(code: 0): UAParser\\Parser::parse(): Argument #1 ($userAgent) must be of type string, null given, called in .../vendor/rinvex/laravel-statistics/src/Jobs/CrunchStatistics.php on line 46 at .../vendor/ua-parser/uap-php/src/Parser.php:37)

fixed by middleware

```
$ua = $request->header('User-Agent');

if (!trim($ua)) {
    abort(403, 'Parser block');
}
```

**Comment by Omranic** [comment]
Thank you, would you be able to send a PR to fix this efficiently? I'll be happy to look into it..
