### ISSUE TITLE
how do I get statistics for a specific Route ? 

### ISSUE THREAD

**Issue by hamzafaouzi** [rinvex/laravel-statistics#8]
hello guys and thanks for this package , I want to know how do I get statistics per Route for example get the statistics for a profile of the user , and how to specify the information to get for example I just want to know page visits and country , thank you .

**Comment by Omranic** [comment]
You can get statistics for specific route as follows
https://github.com/rinvex/laravel-statistics#routes

I believe you can utilize this feature, and search in the parameters field for whatever you want, hope this helps
